tap "tillitis/tkey"
brew "stow"
brew "fish"
brew "tkey-ssh-agent", restart_service: :changed
brew "tkey-verification"
cask "font-fira-code-nerd-font"
cask "font-jetbrains-mono-nerd-font"
cask "ghostty"
